### ISSUE TITLE
Add LatexPrint

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/QuantEconLectureAllPackages#2]
https://github.com/scheinerman/LatexPrint.jl

**Comment by jlperla** [comment]
Hold off on this, though, since I am not sure the package is updated for v1.0

**Comment by arnavs** [comment]
@jlperla It looks like this package hasn't been updated for 4 months. Should we leave this open or look for a replacement?

**Comment by arnavs** [comment]
v0.1.0 passes Travis on Julia 1 though, so I guess I'll add this for now and we can remove later if we think it won't be maintained.
